export default [
  // Global ignore patterns
  {
    ignores: [
      'dist/**',
      '**/dist/**',
      'tarballs/**',
      'node_modules/**',
      'scripts/**',
      'docs/**',
      'playwright-report/**',
      'tests-results/**',
      'songscript/**',
      '**/*.json',
      '**/*.md',
    ],
  },
  // JS Config (ESLint 9+ Flat Config)
  {
    files: ['**/*.js', '**/*.mjs', '**/*.cjs'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        // Browser globals
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        location: 'readonly',
        history: 'readonly',
        HTMLElement: 'readonly',
        HTMLIFrameElement: 'readonly',
        HTMLAudioElement: 'readonly',
        HTMLVideoElement: 'readonly',
        CustomEvent: 'readonly',
        MutationObserver: 'readonly',
        ResizeObserver: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        fetch: 'readonly',
        console: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        URL: 'readonly',
        Event: 'readonly',
        Document: 'readonly',
        Audio: 'readonly',
        HTMLMediaElement: 'readonly',
        MediaMetadata: 'readonly',
        MessageChannel: 'readonly',
        customElements: 'readonly',
        inspect: 'readonly',

        // Node / CommonJS globals
        process: 'readonly',
        module: 'readonly',
        exports: 'readonly',
        require: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',

        // Userscript / Tampermonkey / Violentmonkey globals
        GM_setValue: 'readonly',
        GM_getValue: 'readonly',
        GM_deleteValue: 'readonly',
        GM_listValues: 'readonly',
        GM_addValueChangeListener: 'readonly',
        GM_removeValueChangeListener: 'readonly',
        GM_getResourceText: 'readonly',
        GM_getResourceURL: 'readonly',
        GM_addStyle: 'readonly',
        GM_xmlhttpRequest: 'readonly',
        GM_registerMenuCommand: 'readonly',
        GM_unregisterMenuCommand: 'readonly',
        GM_openInTab: 'readonly',
        GM_setClipboard: 'readonly',
        GM_info: 'readonly',
        GM: 'readonly',
        unsafeWindow: 'readonly',
      },
    },
    rules: { 'no-unused-vars': 'warn', 'no-console': 'off', 'no-alert': 'off', 'no-cond-assign': 'off', 'no-undef': 'warn', 'arrow-body-style': ['error', 'as-needed'] },
  },
];
