import { SREMOTE_ACTIONS, SREMOTE_EVENTS, SREMOTE_STORAGE_KEYS } from '../constants.js';

export const constants = { ACTIONS: SREMOTE_ACTIONS, EVENTS: SREMOTE_EVENTS, STORAGE_KEYS: SREMOTE_STORAGE_KEYS };
